main:
  - name: 关于
    url: /#about
    weight: 10
  - name: 项目
    url: /#projects
    weight: 20
  - name: 联系
    url: /#contact
    weight: 30
  - name: GitHub
    url: https://github.com/qi202
    weight: 40
